version: '3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=wordpress
      - POSTGRES_DB=wordpress
    networks:
      - wordpress
  php-fpm:
    build: 
      context: ./docker/fpm
    volumes:
      - ./wp-cli.phar:/usr/bin/wp:rw,z
      - ./wordpress:/var/www/html:rw,z
      - ./postgresql-for-wordpress/pg4wp:/var/www/html/wp-content/plugins/pg4wp:rw,z
      - ./postgresql-for-wordpress/pg4wp/db.php:/var/www/html/wp-content/db.php:rw,z
    ports:
      - "9000:9000"
    networks:
      - wordpress
    command: >
      sh -c "
      php-fpm
      "
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:rw,z
      - ./wordpress:/var/www/html:rw,z
    networks:
      - wordpress
  php-cli:
    build:
      context: ./docker/cli 
    volumes:
      - ./postgresql-for-wordpress:/development/postgresql-for-wordpress:rw,z
      - ./config/phpunit-watcher.yml:/development/phpunit-watcher.yml:rw,z
      - ./composer.phar:/usr/bin/composer:rw,z
    networks:
      - wordpress
    command: >
      sh -c "
      /usr/bin/composer global require --dev phpunit/phpunit spatie/phpunit-watcher && 
      export PATH="$PATH:$HOME/.composer/vendor/bin:/usr/local/bin" &&
      cd /development/postgresql-for-wordpress &&
      phpunit-watcher watch
      "
volumes:
  pgdata:

networks:
  wordpress: