version: '3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=wordpress
      - POSTGRES_DB=wordpress
    networks:
      - wordpress
  php-fpm:
    image: php:8.3-fpm-alpine
    container_name: php
    restart: unless-stopped
    volumes:
      - ./wp-cli.phar:/usr/bin/wp:rw,z
      - ./wordpress:/var/www/html:rw,z
      - ./postgresql-for-wordpress/pg4wp:/var/www/html/wp-content/plugins/pg4wp:rw,z
      - ./postgresql-for-wordpress/pg4wp/db.php:/var/www/html/wp-content/db.php:rw,z
    ports:
      - "9000:9000"
    networks:
      - wordpress
    command: >
      sh -c "apk add --no-cache postgresql-dev &&
      docker-php-ext-install pdo pdo_mysql mysqli pgsql &&
      php-fpm"
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:rw,z
      - ./wordpress:/var/www/html:rw,z
    networks:
      - wordpress
volumes:
  pgdata:

networks:
  wordpress: